name: glsegenv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip=23.0.1
  - python=3.9.16
  - pip:
      - numpy==1.23.5
      - pandas==1.5.3
      - tqdm==4.64.0
      - matplotlib==3.8.0
      - opencv-python==4.6.0.66
      - protobuf==4.21.12
      - pyproj==3.5.0
      - pytorch==1.12.1
      - torchvision=0.13.1
      - segmentation-models-pytorch==0.3.0
      - pytorch-lightning==1.7.0
      - tensorboard==2.9.1
      - torchmetrics==0.11.0
