defaults:
  - _self_
  - dl4gam_config      # our main configuration file
  - dataset: s2_alps_plus
  - model: unet
  - input: optical
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Set the working directory and the number of processes (for the steps running in parallel)
working_dir: ./data/external/dl4gam
num_procs: 24

hydra:
  run:
    dir: ${working_dir}/logs/${dataset.name}/${current_step}/${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
    formatters:
      colored:
        (): colorlog.ColoredFormatter
        format: "%(log_color)s[%(levelname)s] %(asctime)s - %(name)s: %(message)s (%(filename)s:%(funcName)s:%(lineno)d)"
        log_colors:
          DEBUG: cyan
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: bold_red
    root:
      handlers: [ console, file ]
      level: INFO
      propagate: false

    handlers:
      file:
        filename: ${hydra:run.dir}/${hydra.job.name}.log

    disable_existing_loggers: false
    external_modules: [ pyogrio ]
    external_modules_log_level: WARN