defaults:
  - _self_
  - dl4gam_config      # our main configuration file
  - dataset: s2_alps_plus
  - model: unet
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog


hydra:
  job_logging:
    formatters:
      colored:
        (): colorlog.ColoredFormatter
        format: "%(log_color)s[%(levelname)s] %(asctime)s - %(name)s: %(message)s (%(filename)s:%(funcName)s:%(lineno)d)"
        log_colors:
          DEBUG: cyan
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: bold_red
    root:
      handlers: [ console, file ]
      level: INFO
      propagate: false
    disable_existing_loggers: false
    external_modules: [ pyogrio ]
    external_modules_log_level: WARN