data:
  data_root_dir: '../data/s2_data/patches_orig_r_128_s_128'
  train_dir_name: 'region_r1'
  val_dir_name: 'region_r2'
  test_dir_name: 'region_r3'
  rasters_dir: '../data/s2_data/rasters'
  minmax_scale_data: True
  standardize_data: False
  scale_each_band: False
  data_stats_fn: 'stats_agg.csv'
  train_batch_size: 16
  val_batch_size: 64
  test_batch_size: 64
  num_workers: 16

task:
  seed: 42
  loss:
    name: 'MaskedDist'
    args: {
      distance_type: 'BCE'
    }
  optimization:
    optimizer:
      - name: 'SGD'
        args:
          lr: 0.01
          nesterov: True
          momentum: 0.95
    lr_schedule:
      - name: 'MultiStepLR'
        args:
          milestones: [ 10, 25 ]
          gamma: 0.1

logger:
  save_dir: '../data/scratch/experiments/'
  name: 'unet'

trainer:
  devices: [ 0 ]
  accelerator: 'gpu'
  #  limit_train_batches: 8
  #  limit_val_batches: 4
  log_every_n_steps: 10
  max_epochs: 50

model:
  class: 'SegModel'
  name: 'Unet'
  inputs:
    s2_bands: [ 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B8A', 'B9', 'B10', 'B11', 'B12' ]
    elevation: False
  args:
    encoder_name: 'resnet34'
    encoder_weights: 'imagenet'
    encoder_depth: 5
    activation: 'sigmoid'
    decoder_use_batchnorm: False
    decoder_attention_type: null